version: '3.1'
services:
  proxy_sql:
    image: proxysql/proxysql:2.0.6
    ports:
      - 16032:6032
      - 16033:6033
      - 16080:6080
    volumes:
      - ./db/proxysql/proxysql.cnf:/etc/proxysql.cnf
  mysql1:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: product_db
      MYSQL_USER: proxysqlclient
      MYSQL_PASSWORD: test
      MYSQL_ROOT_HOST: '%'
    ports:
      - 13306:3306
      - 13307:33060
    volumes:
      - ./db/mysql1:/docker-entrypoint-initdb.d/
  mysql2:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: product_db
      MYSQL_USER: proxysqlclient
      MYSQL_PASSWORD: test
      MYSQL_ROOT_HOST: '%'
    ports:
      - 23306:3306
      - 23307:33060
    volumes:
      - ./db/mysql2:/docker-entrypoint-initdb.d/
